promise.then(f1).catch(f2); // Произойдет обработка ошибки
promise.then(f1, f2); // Ошибка будет не обработанной